language: python
python:
  - "3.4"
  - "3.5"
cache:
  directories:
    - $HOME/.cache/pip
    - node_modules
addons:
  postgresql: "9.4"
  firefox: "39.0"

before_install:
  - pip install coveralls flake8 coverage beautifulsoup4 py-dateutil selenium

before_script:
  - python3 -m flake8 .
  - psql -c 'create database doko;' -U postgres
  - head -c 24 /dev/urandom > cookie_secret
  - nvm install stable
  - npm install
  - ./tests/python/selenium_webapp.py &>/dev/null &
  - sleep 2
  - node_modules/gulp/bin/gulp.js dev-build

script:
# - npm test
  - xvfb-run --server-args="-screen 0, 1280x1280x16" tests/python/coverage_run.sh

after_success:
  - coveralls
# - npm coveralls

notifications:
  email:
    on_failure: change
