language: python
python:
  - "3.3"
  - "3.4"
env:
  global:
    - secure: C/Ni0z3WjMsxFtHImuU7OqMlYg8fsON74Xwx/wlhvFHuKfiu8Y6o40/VXSUp7vqhjGJF3jmdWPmwlk2lNg0HwYbTaDBfB9Zr6yHlPKW4uqhWCibIBUN9K0p7Xv1Jp8j3TmSJc1uelLHOtYNYVW8bqyvt7qMqUqYGaGSiH1zU0nA=
    - secure: V0rdSDV1xC8gLK8KC0q9MTe/LHl/yvN51fglqJCY8Keq0FC1rcrIP+Z0nRY5ORxOC4Fv4DJp3uvNktnnW2bVdDDuKc8emEMR/on33Xjp5WcaioADk59YMl+kaMD3DGE1Hqn0/WFnMw8UyYCahBnJuDZMyGJVZyV4FPgGjiMsfU0=
  matrix:
    - "BROWSER='firefox::Linux'"
    - "BROWSER='firefox::OS X 10.6'"
    - "BROWSER='firefox::OS X 10.9'"
    - "BROWSER='firefox::OS X 10.10'"
    - "BROWSER='firefox::Windows XP'"
    - "BROWSER='firefox::Windows 7'"
    - "BROWSER='firefox::Windows 8'"
    - "BROWSER='firefox::Windows 8.1'"
    #- "BROWSER='chrome::Linux'"
    #- "BROWSER='android:4.0:Linux:Android Emulator'"
    #- "BROWSER='android:4.1:Linux:Android Emulator'"
    #- "BROWSER='android:4.2:Linux:Android Emulator'"
    #- "BROWSER='android:4.3:Linux:Android Emulator'"
    - "BROWSER='android:4.4:Linux:Android Emulator'"
    #- "BROWSER='android:5.0:Linux:Android Emulator'"
    #- "BROWSER='iPhone:8.1:OS X 10.10:iPhone Simulator'"
    #- "BROWSER='iPhone:8.1:OS X 10.10:iPad Simulator'"
    #- "BROWSER='safari::OS X 10.10'"
addons:
  postgresql: "9.3"
  sauce_connect: true

# command to install dependencies
install:
  - pip install --use-mirrors -r requirements.txt
  - pip install --use-mirrors -r requirements-testing.txt
  - pip install --use-mirrors coverage coveralls

# database
before_script:
  - psql -c 'create database doko;' -U postgres
  - python3 manage_db.py
  - psql -U postgres -d doko -f tests/fixtures/all-encompassing.sql
  - npm install --python=python2.7
  - python3 webapp.py &

# command to run tests
script: 
  - npm test
  - nosetests --with-coverage --cover-inclusive --cover-branches --cover-tests --cover-html --cover-erase --cover-package=api,db,webapp,pages.api,pages.util,pages.debug,pages.view

after_success: coveralls

notifications:
  irc:
    channels: "irc.freenode.org#sel-columbia"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email:
    on_failure: change
  hipchat:
    rooms:
      secure: O1kfcW59uDkeCOj4NcxHpwCL77pfFxiRosfoRaXedMcV9llJZkZ7IYCc4HLIr52/sTN2eBrFetOoywRL3nrcrfaKIdbW+Dc+IdmesmOI1xMomsY+yWM79q38D1jiwkHbsGQIH4GTSsLSwTf8lFt7KfM3nKAgwEjApq8+zvnSM1w=
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change

