nginx:
  image: "nginx:1.9.5"
  links:
    - "webapp:webapp"
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
webapp:
  image: "selcolumbia/dokomoforms"
  command: bash -c "head -c 24 /dev/urandom > cookie_secret && python webapp.py"
  links:
    - "db:db"
  volumes:
    - ./local_config.py:/dokomo/local_config.py
db:
  image: "mdillon/postgis:9.4"
  environment:
    POSTGRES_PASSWORD: 'password'
    POSTGRES_DB: 'doko'
