webapp-dev:
  build: .
  command: python webapp.py
  volumes:
      - ./:/dokomo
  links:
    - "db-dev:db-dev"
  ports:
    - "8888:8888"
db-dev:
  image: "mdillon/postgis:9.4"
  environment:
    POSTGRES_PASSWORD: 'password'
    POSTGRES_DB: 'doko'
