webapp:
  build: .
  command: python webapp.py
  volumes:
    - ./:/dokomo
  links:
    - "db:db"
  ports:
    - "8888:8888"
db:
  image: "mdillon/postgis:9.4"
  environment:
    POSTGRES_PASSWORD: 'password'
    POSTGRES_DB: 'doko'
