nginx:
  image: "nginx:1.9.9"
  links:
    - "webapp:webapp"
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - /etc/letsencrypt:/etc/letsencrypt
    - /tmp:/tmp
  volumes_from:
    - webapp
webapp:
  image: "selcolumbia/dokomoforms:0.2.9.2"
  command: bash -c "./docker-wait-for-postgres.sh db && head -c 24 /dev/urandom > cookie_secret && python webapp.py"
  links:
    - "db:db"
    - "redis:redis"
  volumes:
    - ./local_config.py:/dokomo/local_config.py
    - /var/www
db:
  image: "mdillon/postgis:9.4"
  environment:
    POSTGRES_DB: 'doko'
redis:
  image: redis:3.2.5
